/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ConfigurableRightsPool,
  ConfigurableRightsPoolInterface,
} from "../ConfigurableRightsPool";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "initialSupply",
        type: "uint256",
      },
    ],
    name: "createPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "setController",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
    ],
    name: "whitelistLiquidityProvider",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ConfigurableRightsPool__factory {
  static readonly abi = _abi;
  static createInterface(): ConfigurableRightsPoolInterface {
    return new utils.Interface(_abi) as ConfigurableRightsPoolInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ConfigurableRightsPool {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ConfigurableRightsPool;
  }
}
