/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAaveATokenV2, IAaveATokenV2Interface } from "../IAaveATokenV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAaveATokenV2__factory {
  static readonly abi = _abi;
  static createInterface(): IAaveATokenV2Interface {
    return new utils.Interface(_abi) as IAaveATokenV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAaveATokenV2 {
    return new Contract(address, _abi, signerOrProvider) as IAaveATokenV2;
  }
}
