/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IBasicToken, IBasicTokenInterface } from "../IBasicToken";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBasicToken__factory {
  static readonly abi = _abi;
  static createInterface(): IBasicTokenInterface {
    return new utils.Interface(_abi) as IBasicTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBasicToken {
    return new Contract(address, _abi, signerOrProvider) as IBasicToken;
  }
}
