/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IBoostDirector,
  IBoostDirectorInterface,
} from "../IBoostDirector";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "getBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_old",
        type: "address",
      },
      {
        internalType: "address",
        name: "_new",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_pokeNew",
        type: "bool",
      },
    ],
    name: "setDirection",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_vaults",
        type: "address[]",
      },
    ],
    name: "whitelistVaults",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBoostDirector__factory {
  static readonly abi = _abi;
  static createInterface(): IBoostDirectorInterface {
    return new utils.Interface(_abi) as IBoostDirectorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBoostDirector {
    return new Contract(address, _abi, signerOrProvider) as IBoostDirector;
  }
}
