/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IClaimRewards, IClaimRewardsInterface } from "../IClaimRewards";

const _abi = [
  {
    inputs: [],
    name: "claimRewards",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IClaimRewards__factory {
  static readonly abi = _abi;
  static createInterface(): IClaimRewardsInterface {
    return new utils.Interface(_abi) as IClaimRewardsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IClaimRewards {
    return new Contract(address, _abi, signerOrProvider) as IClaimRewards;
  }
}
