/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IGatewayRegistry,
  IGatewayRegistryInterface,
} from "../IGatewayRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_tokenSymbol",
        type: "string",
      },
    ],
    name: "getGatewayBySymbol",
    outputs: [
      {
        internalType: "contract IGateway",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_tokenSymbol",
        type: "string",
      },
    ],
    name: "getTokenBySymbol",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGatewayRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IGatewayRegistryInterface {
    return new utils.Interface(_abi) as IGatewayRegistryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGatewayRegistry {
    return new Contract(address, _abi, signerOrProvider) as IGatewayRegistry;
  }
}
