/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ILendingPoolAddressesProviderV2,
  ILendingPoolAddressesProviderV2Interface,
} from "../ILendingPoolAddressesProviderV2";

const _abi = [
  {
    inputs: [],
    name: "getLendingPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILendingPoolAddressesProviderV2__factory {
  static readonly abi = _abi;
  static createInterface(): ILendingPoolAddressesProviderV2Interface {
    return new utils.Interface(
      _abi
    ) as ILendingPoolAddressesProviderV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILendingPoolAddressesProviderV2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILendingPoolAddressesProviderV2;
  }
}
