/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ILiquidator, ILiquidatorInterface } from "../ILiquidator";

const _abi = [
  {
    inputs: [],
    name: "claimStakedAave",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_integration",
        type: "address",
      },
      {
        internalType: "address",
        name: "_sellToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_bAsset",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_uniswapPath",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_uniswapPathReversed",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_trancheAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minReturn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_mAsset",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_useAave",
        type: "bool",
      },
    ],
    name: "createLiquidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_integration",
        type: "address",
      },
    ],
    name: "deleteLiquidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_integration",
        type: "address",
      },
    ],
    name: "triggerLiquidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "triggerLiquidationAave",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_integration",
        type: "address",
      },
      {
        internalType: "address",
        name: "_bAsset",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_uniswapPath",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_uniswapPathReversed",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_trancheAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minReturn",
        type: "uint256",
      },
    ],
    name: "updateBasset",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ILiquidator__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidatorInterface {
    return new utils.Interface(_abi) as ILiquidatorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILiquidator {
    return new Contract(address, _abi, signerOrProvider) as ILiquidator;
  }
}
