/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ImmutableModule,
  ImmutableModuleInterface,
} from "../ImmutableModule";

const _abi = [
  {
    inputs: [],
    name: "nexus",
    outputs: [
      {
        internalType: "contract INexus",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ImmutableModule__factory {
  static readonly abi = _abi;
  static createInterface(): ImmutableModuleInterface {
    return new utils.Interface(_abi) as ImmutableModuleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ImmutableModule {
    return new Contract(address, _abi, signerOrProvider) as ImmutableModule;
  }
}
