/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRevenueRecipient,
  IRevenueRecipientInterface,
} from "../IRevenueRecipient";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_mAssets",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "_percentages",
        type: "uint256[]",
      },
    ],
    name: "depositToPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_mAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "notifyRedistributionAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRevenueRecipient__factory {
  static readonly abi = _abi;
  static createInterface(): IRevenueRecipientInterface {
    return new utils.Interface(_abi) as IRevenueRecipientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRevenueRecipient {
    return new Contract(address, _abi, signerOrProvider) as IRevenueRecipient;
  }
}
