/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISavingsManager,
  ISavingsManagerInterface,
} from "../ISavingsManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_mAsset",
        type: "address",
      },
    ],
    name: "collectAndDistributeInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_mAsset",
        type: "address",
      },
    ],
    name: "collectAndStreamInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_mAsset",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_liquidation",
        type: "uint256",
      },
    ],
    name: "depositLiquidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_mAsset",
        type: "address",
      },
    ],
    name: "distributeUnallocatedInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_mAsset",
        type: "address",
      },
    ],
    name: "lastBatchCollected",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISavingsManager__factory {
  static readonly abi = _abi;
  static createInterface(): ISavingsManagerInterface {
    return new utils.Interface(_abi) as ISavingsManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISavingsManager {
    return new Contract(address, _abi, signerOrProvider) as ISavingsManager;
  }
}
