/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  RevenueRecipientV1,
  RevenueRecipientV1Interface,
} from "../RevenueRecipientV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
    ],
    name: "migrateBPT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class RevenueRecipientV1__factory {
  static readonly abi = _abi;
  static createInterface(): RevenueRecipientV1Interface {
    return new utils.Interface(_abi) as RevenueRecipientV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RevenueRecipientV1 {
    return new Contract(address, _abi, signerOrProvider) as RevenueRecipientV1;
  }
}
