/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  StakingTokenWrapper,
  StakingTokenWrapperInterface,
} from "../StakingTokenWrapper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_stakingToken",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stakingToken",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161033d38038061033d83398101604081905261002f91610044565b60601b6001600160601b031916608052610072565b600060208284031215610055578081fd5b81516001600160a01b038116811461006b578182fd5b9392505050565b60805160601c6102ae61008f600039600060df01526102ae6000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c806306fdde031461006757806318160ddd14610085578063313ce5671461009757806370a08231146100b157806372f702f3146100da57806395d89b4114610119575b600080fd5b61006f610121565b60405161007c91906101ea565b60405180910390f35b6003545b60405190815260200161007c565b61009f601281565b60405160ff909116815260200161007c565b6100896100bf3660046101bc565b6001600160a01b031660009081526004602052604090205490565b6101017f000000000000000000000000000000000000000000000000000000000000000081565b6040516001600160a01b03909116815260200161007c565b61006f6101af565b6001805461012e9061023d565b80601f016020809104026020016040519081016040528092919081815260200182805461015a9061023d565b80156101a75780601f1061017c576101008083540402835291602001916101a7565b820191906000526020600020905b81548152906001019060200180831161018a57829003601f168201915b505050505081565b6002805461012e9061023d565b6000602082840312156101cd578081fd5b81356001600160a01b03811681146101e3578182fd5b9392505050565b6000602080835283518082850152825b81811015610216578581018301518582016040015282016101fa565b818111156102275783604083870101525b50601f01601f1916929092016040019392505050565b60028104600182168061025157607f821691505b6020821081141561027257634e487b7160e01b600052602260045260246000fd5b5091905056fea2646970667358221220e1d906a0945007b83437e5e5027e730534f0ef15602b19409c8b661fe39a6a0264736f6c63430008020033";

export class StakingTokenWrapper__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    _stakingToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<StakingTokenWrapper> {
    return super.deploy(
      _stakingToken,
      overrides || {}
    ) as Promise<StakingTokenWrapper>;
  }
  getDeployTransaction(
    _stakingToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_stakingToken, overrides || {});
  }
  attach(address: string): StakingTokenWrapper {
    return super.attach(address) as StakingTokenWrapper;
  }
  connect(signer: Signer): StakingTokenWrapper__factory {
    return super.connect(signer) as StakingTokenWrapper__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StakingTokenWrapperInterface {
    return new utils.Interface(_abi) as StakingTokenWrapperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StakingTokenWrapper {
    return new Contract(address, _abi, signerOrProvider) as StakingTokenWrapper;
  }
}
