name: Deploy preview

on:
  pull_request:

jobs:
  build_and_preview_protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn codegen:typechain
      - run: yarn nx run-many --all --parallel --target=lint
      - run: yarn nx run protocol:build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: protocol_deploy
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MSTABLE_APPS_PROTOCOL }}"
          expires: 30d
          projectId: mstable-apps-protocol
          entryPoint: apps/protocol
          target: mstable-apps-protocol
      - run: |
          echo ":rocket: Deploy protocol app on ${{ steps.protocol_deploy.details_url }}" >> $GITHUB_STEP_SUMMARY
  build_and_preview_governance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn nx run-many --all --parallel --target=lint
      - run: yarn codegen:typechain
      - run: yarn nx run governance:build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: governance_deploy
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MSTABLE_APPS_GOVERNANCE }}"
          expires: 30d
          projectId: mstable-apps-governance
          entryPoint: apps/governance
          target: mstable-apps-governance
      - run: |
          echo ":rocket: Deploy governance app on ${{ steps.governance_deploy.details_url }}" >> $GITHUB_STEP_SUMMARY
