name: Deploy preview

on:
  pull_request:

jobs:
  build_and_preview_protocol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install
      - run: yarn codegen:typechain
      - run: yarn nx run-many --all --parallel --target=lint
      - run: yarn nx run protocol:build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MSTABLE_APPS_PROTOCOL }}"
          expires: 30d
          projectId: mstable-apps-protocol
          entryPoint: apps/protocol
          target: mstable-apps-protocol
  build_and_preview_governance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v2
      - run: yarn install
      - run: yarn nx run-many --all --parallel --target=lint
      - run: yarn codegen:typechain
      - run: yarn nx run governance:build --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MSTABLE_APPS_GOVERNANCE }}"
          expires: 30d
          projectId: mstable-apps-governance
          entryPoint: apps/governance
          target: mstable-apps-governance
